### ISSUE TITLE
Preceding a topic name with an underscore will ignore an existing AVRO schema

### ISSUE THREAD

**Issue by erikvullings** [Landoop/kafka-topics-ui#100]
By preceding my topic with an underscore, e.g. _configuration, the AVRO _configuration-key, and _configuration-value schemas were ignored, and my topic was displayed as binary. After renaming it to configuration (and subsequent schema files, configuration-key and configuration-value), the AVRO messages were displayed correctly.

**Comment by andmarios** [comment]
Hi @erikvullings . I have trouble replicating your issue as you can see below:
![screenshot_20180209_222411](https://user-images.githubusercontent.com/1239679/36048459-00d0de34-0de8-11e8-8c79-b65884d6cc1e.png)

Could it be that you push some messages to your topic that confuse REST Proxy?
I don't think this issue is on us.
