### ISSUE TITLE
Topic Message Not Loading

### ISSUE THREAD

**Issue by buntydevops** [Landoop/kafka-topics-ui#107]
![capture](https://user-images.githubusercontent.com/30381120/37698293-0f4c854e-2cb0-11e8-8de9-1da76f83ad04.PNG)

Getting this error in Chrome

**Comment by Antwnis** [comment]
Can you provide some additional info ?

- Which version of Kafka REST
- Which version of kafka-topics-ui
- How are you serving kafka-topics-ui (nginx / httpd / docker ) 
- How is your web-server configured ( have u enabled CORS )
- How is Kafka REST configured

**Comment by buntydevops** [comment]
Kafka Topic UI Version : KAFKA-TOPICS-UI v0.9.3
How are you serving kafka-topics-ui : Docker
How is your web-server configured : CORS enabled  in kafka-rest.properties
How is Kafka REST configured
Connects with Broker , Schema Registry over SSL and Zookeeper on Non SSL
We are using Confluent Kafka 3.3.0

**Comment by Antwnis** [comment]
Ellaborate on how Kafka REST is configured. I am assuming that you have not enabled the v2 API - by providing the bootstrap brokers configuration in the proxy

i.e. look at https://github.com/Landoop/kafka-topics-ui#common-issues

**Comment by buntydevops** [comment]
My kafka-rest.properties looks like below

listeners=https://rest-hostname.mytest.com:8083
port=8083
schema.registry.url=schema-hostname.mytest.com:8443
zookeeper.connect=zk0101.mytest.com:2181,zk0102.mytest:2181,zk0103.mytest.com:2181/kafka
bootstrap.servers=SSL://kb0101.mytest.com:9093,SSL://kb0102.mytest.com:9093,SSL://kb0103.mytest.com:9093
ssl.keystore.location=/opt/tmp/ssl/<hostname>.jks
ssl.keystore.password=xxxxx
ssl.key.password=xxxx
ssl.truststore.location=/opt/tmp/ssl//umtruststore.jks
ssl.truststore.password=xxxxx
access.control.allow.methods=GET,POST,PUT,DELETE,OPTIONS
access.control.allow.origin=*

**Comment by Antwnis** [comment]
```schema.registry.url=schema-hostname.mytest.com:8443```

The above entry does not look correct. The schema-registry config has to be a URL and thus start with either http:// or https://

**Comment by buntydevops** [comment]
I changed it to https but still same issue, topic messages do not load.
![capture](https://user-images.githubusercontent.com/30381120/37784033-ef80e23a-2dc4-11e8-9835-e311d79505c2.PNG)

**Comment by Antwnis** [comment]
Is Kafka REST working ? Have you verified that it works by pulling messages directly using the REST APIs ?

**Comment by buntydevops** [comment]
Yes it works

![image](https://user-images.githubusercontent.com/30381120/37784554-162a8cbe-2dc6-11e8-955c-41a9180476ad.png)

**Comment by buntydevops** [comment]
![image](https://user-images.githubusercontent.com/30381120/37784729-7ac4d814-2dc6-11e8-909a-14a6f6a6c5c3.png)

**Comment by olmstead** [comment]
I'm having a similar issue.  When I only have a few messages in a topic, they load, but as the topic size increases,  topic-ui eventually shows no items in the topic.  I believe this is because the UI is trying to get all the message for one topic in one request.   If that's this case, this tool isn't going to work in real environments with millions of messages, or even hundreds unless you bump MAX_BYTES way up.  Does the REST API not have a way to page the topic messages rather than requesting all at once?

**Comment by andmarios** [comment]
Actually we request up to `MAX_BYTES` from REST Proxy, so it will not return more messages than needed.
You can also tweak `RECORD_POLL_TIMEOUT` because for a large topic, the REST Proxy will take too long to return entries from the start of the topic.

The bug you hit though, probably comes from REST Proxy itself as it has a default timeout of just 1000ms, which is way too small.
In order to fix this, you should set `consumer.request.timeout.ms=30000` in the REST Proxy. Why 30000? Because REST Proxy has a bug (we have reported it upstream) and treats the `consumer.request.timeout.ms` the same as `request.timeout.ms` which are actually two different values in the REST Proxy context.

Have a look here as well: https://github.com/Landoop/kafka-topics-ui/tree/master/docker#kafka-rest-proxy-configuration

Also you can test your kafka cluster response times yourself, using the kafka-console-consumer command:

    time kafka-console-consumer --bootstrap-server PLAINTEXT://broker.url:9092 --topic topic.name --from-beginning --max-messages 100

**Comment by olmstead** [comment]
After a certain size, my topics always show up as empty. I've increased consumer request timeout on the REST proxy server to 30000 and MAX_SIZE on the the UI to 1000000.  Just saw post above, will try increasing the poll timeout.

**Comment by olmstead** [comment]
My poll timeout is 12000.  Still topics show as empty after a certain size.  Is this tool intended for production use?

**Comment by andmarios** [comment]
As explained, the `MAX_BYTES` is a parameter that is passed to REST Proxy. So the REST Proxy itself will never return more data than this.

Kafka Topics UI does have to work within the limitations of REST Proxy. You can get much more functionality and better performance from Lenses, our enterprise offering, which does not rely on rest proxy.
http://www.landoop.com/kafka-lenses/

**Comment by olmstead** [comment]
Thank Marios!  Given what I know about Kafka topics, your explanation makes sense as to why paging messages is not trivial.   I was able to get the topic empty message to stop showing, and that works for me.  I had the wrong setting for the request timeout on the REST proxy.   For the Confluent docker container (cp-kafka-reset) you need to set KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS=30000

**Comment by andmarios** [comment]
Glad you worked it out! Keep in mind that Kafka returns recent messages quicker than old ones (mainly because new ones are usually in the OS cache) and its performance depends on the cluster load. This is why I mentioned the kafka-console-consumer command as a way to test your cluster's performance.

**Comment by jglambed** [comment]
I ll close this issue, as solved. Feel free to reopen it.
