### ISSUE TITLE
Unable to display certain topics

### ISSUE THREAD

**Issue by colleen-love** [Landoop/kafka-topics-ui#110]
I'm running fast-data-dev:1.0.1. When I try to load certain topics via the UI it displays "Topic is empty" and the following message appears in the console:

HTTP ERROR: Failed at method [GET] [/api/kafka-rest-proxy/consumers/kafka_topics_ui_avro_2018-04-16-12-23-19-016/instances/kafka-topics-ui-avro/records?timeout=5000&max_bytes=50000] with error: 
{
  "data": {
    "error_code": 50002,
    "message": "Kafka error: Error deserializing key\/value for partition ARTICLE_DEDUPE-0 at offset 0. If needed, please seek past the record to continue consumption."
  },
  "status": 500,
  "config": {
    "method": "GET",
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "jsonpCallbackParam": "callback",
    "url": "\/api\/kafka-rest-proxy\/consumers\/kafka_topics_ui_avro_2018-04-16-12-23-19-016\/instances\/kafka-topics-ui-avro\/records?timeout=5000&max_bytes=50000",
    "data": "",
    "dataType": "json",
    "headers": {
      "Content-Type": "application\/vnd.kafka.v2+json",
      "Accept": "application\/vnd.kafka.avro.v2+json"
    }
  },
  "statusText": "Internal Server Error"
}

Interestingly, there is no issue deserializing the same schema on different topics.

**Comment by andmarios** [comment]
Hi @collinscangarella, it seems that one or more records in your topic (the error is about the first message produced) have different serialization than the rest, so REST Proxy can not decode them.

Unfortunately this is not something the current Kafka Topics UI can overcome.

You can give a try to our `landoop/kafka-lenses-dev`, which includes our Lenses software[1] instead of the UIs and is more flexible when it comes to deserialization.

[1] https://www.landoop.com/downloads/

**Comment by colleen-love** [comment]
I don't think the REST proxy is trying to decode them. The key is a string and the value is avro - everything appears in binary (as the REST proxy doesn't support avro when the key and value are not both avro).

**Comment by jglambed** [comment]
Hello @collinscangarella Sorry for the late reply,
I was investigating your issue, and I cannot really reproduce it.
Is it possible that you have evolved the AVRO value schema to something incompatible?

Also can you please enable the console debug logs, and share them with us?

**Comment by colleen-love** [comment]
There is only one version of the avro schema. Here's the console output when I load the topic:

https://pastebin.com/7UTw7GN7

**Comment by jglambed** [comment]
Thank you for providing the logs.

Ok, as we can see in the logs, Kafka Topics UI is trying AVRO deserialiser that it fails, then JSON and in its third try, BINARY witch is working but polls 0 messages. 
This is probably happening due to time out. 

As you can see in Kafka Topics UI readme file, 

> Important: For Kafka REST Proxy 3.2.x you should set consumer.request.timeout.ms=30000. Without this option, Kafka REST Proxy will fail to return messages for large topics.

Also it is possible this is happening due record poll timeout, witch default value is 2000ms
You can change it from the docker, by setting `RECORD_POLL_TIMEOUT` to 8000ms
or by changing the same parameter in `env.js` file

I hope that helps
