### ISSUE TITLE
Unable to load all topics

### ISSUE THREAD

**Issue by FranckyBoyX** [Landoop/kafka-topics-ui#145]
Kafka brokers has about 3K+ topics, it looks like kafka-topics-ui is trying to load the details on all of them but eventually stops and crashes. Is there any lazy-loading config?

**Comment by qiao-meng-zefr** [comment]
I'm having the same issue here. When there are a lot of kafka topics, the UI takes a long time to load because it actually makes a call on each topic to kafka rest.

It seems the topic-ui is trying to retrieve partitions and replications information, I say we don't need to see that until I click on a specific topic.

**Comment by jglambed** [comment]
Hi @FranckyBoyX I am afraid at the moment there isn't any. What @qiao-meng-zefr suggested, a way to configure what info you are able to see in the topics list could probably make it for most cases but I cannot give you an ETA.

**Comment by jglambed** [comment]
Fixed from @suanmeiguo as per #146 
We added a lazy load flag in env.js. You can set `LAZY_LOAD_TOPIC_META: true`
