### ISSUE TITLE
i found message has some different, some only have RAW DATA, but some have TABLE

### ISSUE THREAD

**Issue by Cloud-Leung** [Landoop/kafka-topics-ui#80]
![1](https://user-images.githubusercontent.com/16982375/27681810-fbe8da08-5cf2-11e7-981f-57f175b0c366.png)

![2](https://user-images.githubusercontent.com/16982375/27682045-bbd9beae-5cf3-11e7-8f2a-f711aa2307b0.png)

just like this，Is that the way I push messages?

i know this should not be a issues, i just really can't understand this , so i hope you can help me  .....

**Comment by Antwnis** [comment]
It depends on how you serialize the data when you write them into a topic.

If the data is **structured** i.e. either Avro or Json then we do provide the additional (table) + (tree) views.

If the data is **un-structured** i.e. Binary then you only get to see the (raw) view

**Comment by Cloud-Leung** [comment]
thank you , i get it.

**Comment by Cloud-Leung** [comment]
but like up the image ,my data should be structured,it's a json data.
I just used StringSerializer when I was pushing data to kafka，Am I using the wrong one?
if i used the wrong one ,which one should i use ?
![qq 20170704154434](https://user-images.githubusercontent.com/16982375/27820128-e665d6dc-60cf-11e7-8812-5b7018c595dd.png)

these are the kafka Serializer list .

**Comment by Antwnis** [comment]
Your **value** seems to be a properly structured JSON message (using StringSerializer) 
Your **key** seems to be an Integer and is a 32 bit number that gets translated to 4 bytes - so number 1 is translated to `\\0000 \\0000 \\0000 \\0001`

Integer is also limited by `Integer.MAX` - so you could possibly standardise in Json/Json (for both Key and Value). This could make your life easier overall - as otherwise you would need to "remember" what the Key is - and could make your topic harder to be read by non Java apps  

@jglambed what do you think about (BYTE i.e. INTEGER) + (JSON) Does it make sense to provide the (table) & (tree) view ?

**Comment by Cloud-Leung** [comment]
it does work，i set the key to the null ,then the data can be show in the table .
i don't care about what the key value, i set the integer value only want to let my datas are evenly in partition .
very thank you !
