### ISSUE TITLE
Consumer Message Limits

### ISSUE THREAD

**Issue by pliew** [Landoop/kafka-topics-ui#81]
Hi,

I currently have a topic that has 180 messages in it.  I notice that it consistently fetches 38 messages for this specific topic.  I am able to see the remainder topics by setting the specific offset, but that doesn't seem very intuitive.

I have used both the REST proxy and the kafka-console-consumer to verify that the topic does indeed contain all the messages, so I am at a loss as to why this would happen.

I assume the REST proxy might be sending down a limited number of messages?

To make things even more confusing, I have another topic that has over 5000 messages and the topics-ui seems to only fetch 36 rows, and setting the offset doesn't allow me to jump to the proper records.

I am using the fast-data-dev docker image and a jdbc source connector to load the data.

**Comment by kongo2002** [comment]
Hi,

I am no expert on the topics UI myself since I am experimenting for a couple of hours only myself. I think the amount of data you get displayed is limited by the setting `MAX_BYTES` in your `env.js` file which defaults to 50kb

```
MAX_BYTES: "50000"
```

However I would expect that the UI fetches the next/remaining entries via pagination which doesn't work for me. Maybe someone else can give some hints on that?

Cheers,
Gregor

**Comment by andmarios** [comment]
@pliew I think @kongo2002's suggestion is the most plausible solution. Could you give it a try?

@kongo2002, I don't think pagination works this way for Topics UI. I will tag @jglambed who may be able to explain things better.

**Comment by jglambed** [comment]
@kongo2002 UI pagination works only for the fetched data. To fetch more data you must either change the MAX_BYTES or change the offset to the desired one.

**Comment by pliew** [comment]
Thanks @kongo2002 @andmarios,

I can confirm that the MAX_BYTES does indeed fix that issue.  I can also confirm that the pagination only works on what is fetched.  If you want to retrieve items that weren't retrieved in the first MAX_BYTES call, then you need to set the "offset" value.

I think there is an underlying bug with KAFKA as the second odd problem I noted still exists, but only for one particular topic.  Basically, when I select the topic I get all the messages that can fit in the MAX_BYTES.  Whenever I try to retrieve messages using the offset, I get an empty set.  So for example, if there are 700 messages showing, and I set a message to offset 600 (guaranteeing at least 100 messages), I get 0.  To make things even more confusing when I set the offset to 0, I get an empty set returned.

I replicated the REST calls being made manually and it has the same issue as well.  Basically here is what works:
1. Creation of instance
2.  Call to /assignments
3.  Call to /positions/beginning
4.  Fetch records

This scenario doesn't work:
1. Creation of instance
2.  Call to assignments
3.  Call to /positions (setting the offset)
4.  Fetch records

This always results in an empty set for this topic.

Now this only happens with ONE particular topic.  All others seem to work fine.  The only difference I can think of is that this topic has a much larger amount of messages.

**Comment by andmarios** [comment]
For this issue, you have to adjust Kafka REST Proxy. Try setting `consumer.request.timeout.ms=30000`. Due to a bug, you can't set it to a lower value (though the default is just 1000).

This will solve the empty dataset on large topics. I am not sure how it will deal with the second issue (go to a specific offset in a large topic), especially if the topic contains compressed messages.

**Comment by pliew** [comment]
Thanks @andmarios 
I will try this out.  I know this isn't a kafka-topics-ui issue, and I appreciate the guidance.

**Comment by kongo2002** [comment]
Yes, I can confirm what @pliew just described. On rather large topics I cannot set the offset to a specific value which basically makes the UI useless for these topics.

I will try if adjusting the consumer request timeout on the REST proxy helps.

**Comment by andmarios** [comment]
@pliew No problem, more than anything, we are happy when our UIs are used and enjoyed!

@kongo2002 Please try the REST Proxy setting, it should've been part of our docs for the current release but it slipped past us.

**Comment by kongo2002** [comment]
@andmarios increasing `consumer.request.timeout.ms` does help indeed - thanks!

Are there any plans on supporting a pagination approach that does the offset increase by itself? I find this usage rather unintuitive to be honest.

**Comment by andmarios** [comment]
Cool! About the pagination approach I will ask once again @jglambed to step in.

**Comment by pliew** [comment]
The `consumer.request.timeout.ms` setting works.  I agree with @kongo2002 that it would be more intuitive to show pagination across the total messages in the topic, and if the page is selected where the message doesn't exist then make a request from that offset.

Another nice feature would be to display the max offset or the total number of messages so you can set the "offset" field appropriately.

**Comment by andmarios** [comment]
Here we touch Kafka's territory. It can be very difficult and even impossible to know the minimum and maximum offset. I know that @jglambed and the rest of the team have been searching for a solution for quite some time but in the end it is Kafka semantics.

When you create a consumer in Kafka, you can either set it to earliest (so it gets the minimum offset) or latest (where it does not get any offset, only new messages). Kafka will periodically delete messages that are too old, or when the log size gets bigger than a set threshold, making the minimum offset a bit difficult to get reliably. Maximum (latest) offset is also a rolling target, since the only way to get it is to consume all messages, which can be a bit hard to do from a javascript app in your browser.
